### ISSUE TITLE
Basic idea of the project 

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#1]
1. The main aim of the project is to make a plotter which is customized for the signal processing engineers and which can process signals very quickly.
New suggestions are most welcome please feel free to create new issues

**Comment by pearlpandz** [comment]
Just create plotted concept logo, 
![image](https://user-images.githubusercontent.com/12746886/95953867-1c326200-0e18-11eb-95aa-886e788e5fc2.png)

**Comment by ayan-biswas0412** [comment]
Nice work @pearlpandz can you keep it as png file inside the src/assets and also make a gif which will be shown when the site will be loading

**Comment by pearlpandz** [comment]
> Nice work @pearlpandz can you keep it as png file inside the src/assets and also make a gif which will be shown when the site will be loading 

Added as svg file. 
I can't able to push my code in your repository... I don't know why

**Comment by ayan-biswas0412** [comment]
> > Nice work @pearlpandz can you keep it as png file inside the src/assets and also make a gif which will be shown when the site will be loading
> 
> Added as svg file.
> I can't able to push my code in your repository... I don't know why

you have to fisrt fork the repo and then you have to make a PR

**Comment by pearlpandz** [comment]
PR done
