### ISSUE TITLE
[New Work] Design a navbar for homepage

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#11]
**What is the work should be done please be clear and short about the work**
Design a Navbar in the homepage add some basic tabs only but the navbar should be mobile compatible.Choose a colour scheme of your choice for the homepage 

**What the work is all about? Is there any specific files that need to be changed please include those.**
the work should be creative and the navbar component should be under src/components/Navbar.js and the navbar should be mobile view compatible
The component should be imported to the src/pages/Homepage.js

**The Best way to implement this (if any) **
use the react bootstrap

**Additional context** 
no

**Comment by femakin** [comment]
What about me trying this

**Comment by ayan-biswas0412** [comment]
@femakin ok you can do it also

**Comment by femakin** [comment]
Should Navbar be a component that would be imported into the Homepage?

**Comment by ayan-biswas0412** [comment]
> Should Navbar be a component that would be imported into the Homepage?

yeah it will be like that

**Comment by iamKaartik** [comment]
Can i work on it

**Comment by ayan-biswas0412** [comment]
> Can i work on it

yah you can do but again the work should be creative and the navabr component should be under src/components/Navbar.js and the navbar should be mobile view compatible

**Comment by iamKaartik** [comment]
I'll try my best. And thank you for assigning me this task.

**Comment by ayan-biswas0412** [comment]
@femakin @iamKaartik are you working on this ?

**Comment by iamKaartik** [comment]
Yes I'm

**Comment by femakin** [comment]
Can I still work on this

**Comment by ayan-biswas0412** [comment]
> Can I still work on this

yes you are most welcome
