### ISSUE TITLE
[New Work] Make a switch button and enhance the theme

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#113]
**What is the work should be done please be clear and short about the work**
Now there is a change button for theme make it a switch button just like the hacktoberfest website 
![image](https://user-images.githubusercontent.com/52851184/97022736-1d7b3180-1572-11eb-81c9-e5068eef2dc5.png)
And also enhance the theme currently the theme is not changing for the following buttons 
![image](https://user-images.githubusercontent.com/52851184/97022805-31bf2e80-1572-11eb-8d32-77e454625a2d.png)
change that also

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Be creative that is the only matters 

**The Best way to implement this (if any) **
Just be creative to your work and any type of extra creativity in theming is also acceptable

**Comment by anubhavvs** [comment]
Hey, I want to work on this, can you assign it to me?

**Comment by ayan-biswas0412** [comment]
@anubhavvs yeah go ahead
