### ISSUE TITLE
[New Work] Make a contributor page by parsing the Readme file

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#115]
**What is the work should be done please be clear and short about the work**
All the contributos are given in the Readme file now you have to make a react page by parsing the data and generate it dynamically such that any change in Readme shoud also reflect in the React page .
There should be a button " Contributors" in the navbar and the footer => onclick => should redirect to the page

**What the work is all about? Is there any specific files that need to be changed please include those.**
Be creative and make the best possible thing

**The Best way to implement this (if any) **
NA
**Additional context** 
NA

**Comment by jmannfeld** [comment]
Hi! Can I start working on this issue? 😄

**Comment by ayan-biswas0412** [comment]
@jmannfeld yeah go ahead
