### ISSUE TITLE
[New Work] Footer component design

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#18]
**What is the work should be done please be clear and short about the work**
Design a footer for the homepage

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Use the react bootstrap library and make a footer for this

**The Best way to implement this (if any) **
NA

**Additional context** 
NA

**Comment by femakin** [comment]
Can I work on this, please

**Comment by ayan-biswas0412** [comment]
ye @femakin go ahead

**Comment by femakin** [comment]
Alright @ayan-biswas0412

**Comment by ayan-biswas0412** [comment]
@femakin are you working on this?

**Comment by femakin** [comment]
Yes

**Comment by femakin** [comment]
Please help review @ayan-biswas0412

**Comment by iamKaartik** [comment]
> **What is the work should be done please be clear and short about the work**
> Design a footer for the homepage
> 
> **What the work is all about ? Is there any specific files that need to be changed please include those.**
> Use the react bootstrap library and make a footer for this
> 
> **The Best way to implement this (if any) **
> NA
> 
> **Additional context**
> NA

Can i do this

**Comment by ayan-biswas0412** [comment]
> > **What is the work should be done please be clear and short about the work**
> > Design a footer for the homepage
> > **What the work is all about ? Is there any specific files that need to be changed please include those.**
> > Use the react bootstrap library and make a footer for this
> > **The Best way to implement this (if any) **
> > NA
> > **Additional context**
> > NA
> 
> Can i do this

yah you can make one if if want and do a proper PR but the work should be really creative ...The footer component should be really eye-catchy and the footer should be under src/components/Footer.js

**Comment by iamKaartik** [comment]
Sure. Thank you
