### ISSUE TITLE
[New Work] component charts should be added

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#22]
**What is the work should be done please be clear and short about the work**
component for rendering graphs using chart.js the component should take props of x y z coordinate and render the chart in the page

**What the work is all about ? Is there any specific files that need to be changed please include those.**
use chartjs npm package

**The Best way to implement this (if any) **
NA

**Additional context** 
NA

**Comment by varunpappu** [comment]
@ayan-biswas0412 can you assign this to me.

**Comment by ayan-biswas0412** [comment]
@varunpappu yes you can go with this ...

**Comment by ayan-biswas0412** [comment]
@varunpappu are you working ?

**Comment by varunpappu** [comment]
will be working on it. @ayan-biswas0412 .

**Comment by ayan-biswas0412** [comment]
> will be working on it. @ayan-biswas0412 .

ok

**Comment by varunpappu** [comment]
@ayan-biswas0412 What type of chart are you expecting to be displayed? Also, not every chart support z axis.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 What type of chart are you expecting to be displayed? Also, not every chart support z axis.

Like the GNU octave or MATLAB type plotting

**Comment by varunpappu** [comment]
Ok I will look for packages but chartjs doesn't support 3d visual I guess. Also what type of chart, bar graph,line ,pie chart? @ayan-biswas0412

**Comment by ayan-biswas0412** [comment]
> Ok I will look for packages but chartjs doesn't support 3d visual I guess. Also what type of chart, bar graph,line ,pie chart? @ayan-biswas0412

First you go for line ...later on there will be more issue coming on the customization of charts
