### ISSUE TITLE
[New Work] Make a theme for the web app 

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#26]
**What is the work should be done please be clear and short about the work**
A toggle button is needed and the top right corner of the website for switching between dark and light theme .

**What the work is all about? Is there any specific files that need to be changed please include those.**
Check the various sites which uses conventional method for theming and implement this

**The Best way to implement this (if any) **
you have to use the react-bootstrap for the theming purpose . and using a toogle button you have to change between the themes.

**Additional context** 
NA

**Comment by Nagasandesh** [comment]
Hey @ayan-biswas0412 , I would like to contribute. Can I use JavaScript to add toggle button

**Comment by ayan-biswas0412** [comment]
@Nagasandesh yeah go ahead

**Comment by Nagasandesh** [comment]
@ayan-biswas0412 already someone has added the toggle button, can you specify what should I do

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 already someone has added the toggle button, can you specify what should I do

I want the toogle button to look like the hacktoberfest official website's tooglw button and also the theme is chaning but the colour of the panel as welll as many texts are not changing so they become invisible in dark mode so you have to fix it
