### ISSUE TITLE
[New Work] Make one pager blog page for the website

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#27]
**What is the work should be done please be clear and short about the work**
A blog page should be markdown based which supports markdown.Make a simple blogpage first and make a PR.
There should be one button in the navbar named Blog and on click it should go to the blog page

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Show your own creativity .Use yarn packages which are available in market 

**The Best way to implement this (if any) **
NA

**Additional context** 
NA

**Comment by vunderkind** [comment]
Hey @ayan-biswas0412 - can I work on this? It doesn't look like it's done yet.

**Comment by ayan-biswas0412** [comment]
@varunpappu yeah go ahead ...

**Comment by ayan-biswas0412** [comment]
@varunpappu are you working ??

**Comment by varunpappu** [comment]
@ayan-biswas0412 I think this has been assigned to the wrong person..

**Comment by ayan-biswas0412** [comment]
@varunpappu  sorry  ....... 

Hello @vunderkind are you working in it ??

**Comment by vunderkind** [comment]
> @varunpappu  sorry  .......  I have mistakenly mentioned you
> 
> Hello @vunderkind are you working in it ??

Hey thanks for the nudge. I'll ship this by weekend. Got caught up in some political instability in my country.

Sorry for not updating you about this.

Thanks!
