### ISSUE TITLE
[New Work] Design a Code editor panel for the website

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#33]
**What is the work should be done please be clear and short about the work**
design a simple component in which code can be written only (no compilation neeed)

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Just like google colab or any coding platform like Hackerearth type code writing panel is neeed

**The Best way to implement this (if any) **
Shouw your maximum creativitiy for this

**Additional context** 
NA

**Comment by ankit-rawani** [comment]
Using codemirror would be great for this purpose.
I may wanna try it if you provide me where exactly you need the code editor on the site.

**Comment by ayan-biswas0412** [comment]
> Using codemirror would be great for this purpose.
> I may wanna try it if you provide me details about where exactly you need the code editor on the site.

I want the code editor just below the charts which are there in the homepage and the code editor shoulbe be resized accordingly with the screen size and mobile screen compatible and you can show your creativity with full freedom .. and you can work with this.

**Comment by ankit-rawani** [comment]
Okay nice

**Comment by ayan-biswas0412** [comment]
@ankit-rawani nice work
