### ISSUE TITLE
[New Work] Fix the mobile view navbar element spacing

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#40]
**What is the work should be done please be clear and short about the work**
![image](https://user-images.githubusercontent.com/52851184/96272407-ad0d6700-0feb-11eb-8468-bb86bdc536ac.png)
See for smaller mobiles the search bar is coming too close to the search button fix this such that it spaces a little in case of small mobile screens

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Show your creativity here

**The Best way to implement this (if any) **
do whatever way you like

**Additional context** 
NA

**Comment by wojciechwachowiak** [comment]
Can you assign this to me?

**Comment by ayan-biswas0412** [comment]
@wojciechwachowiak ya go ahead.

**Comment by ayan-biswas0412** [comment]
@wojciechwachowiak you are working or  not ?

**Comment by abdulsamad** [comment]
Can I work on this?

**Comment by ayan-biswas0412** [comment]
@abdulsamad yeah go ahead

**Comment by ayan-biswas0412** [comment]
good work @abdulsamad

**Comment by abdulsamad** [comment]
Thanks @ayan-biswas0412
