### ISSUE TITLE
[New Work] fix the mobile view layouting of the charts which are rendered in the screen

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#41]
**What is the work should be done please be clear and short about the work**
The charts are not fitted in screen in case of mobile view 

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Do whatever way you want

**The Best way to implement this (if any) **
Do whatever way you want

**Additional context** 
NA

**Comment by MissyM2** [comment]
Hi, there, I'd like to work on this.  Can I?

**Comment by ayan-biswas0412** [comment]
@MissyM2 yeah sure ..I am assigning you then

**Comment by ayan-biswas0412** [comment]
> Hi, there, I'd like to work on this. Can I? Do you have any other preferences, instructions?

no there is no preferences, we want to see the love by open-source contribution just show your creativity

**Comment by ayan-biswas0412** [comment]
nice work @MissyM2 you can see other active issues in the repo .. nice work @MissyM2

**Comment by MissyM2** [comment]
Thank you!  I will look!

Missy
missymaloney1@gmail.com
