### ISSUE TITLE
[New Work] Build a component for rendering charts

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#42]
**What is the work should be done please be clear and short about the work**
there are two charts rendered in the homepage , now design a component which will take the co-ordinate values as props and there will be a selector options for char type be it the bar chart or the line chart .. The default will be the bar .

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Make the comonent inside the folder components and render it in homepage

**The Best way to implement this (if any) **
Be creative we always welcome creative people

**Additional context** 
NA

**Comment by sprakash57** [comment]
May I take this up?

**Comment by ayan-biswas0412** [comment]
yah you can do this @sprakash57

**Comment by sprakash57** [comment]
Thank you!!

**Comment by sprakash57** [comment]
Hi @ayan-biswas0412 I have raised PR [https://github.com/indeplot/indeplot/pull/68](https://github.com/indeplot/indeplot/pull/68) and it's ready for review.

**Comment by ayan-biswas0412** [comment]
nice work @sprakash57
