### ISSUE TITLE
[New Work] Make a code of conduct page

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#53]
**What is the work should be done please be clear and short about the work**
See the CODE_OF_CONDUCT.md file and make a react page '/codeofconduct' which will show the content of the markdown file 
, make necessary styiling and parsing technique any update in the .md file should reflect in the page

**What the work is all about ? Is there any specific files that need to be changed please include those.**
NA

**The Best way to implement this (if any) **
NA

**Additional context** 
Be creative as much as you can for designing the page

**Comment by dudakp** [comment]
hello, can I take this one?
I would like to use lib `react-markdown`

**Comment by ayan-biswas0412** [comment]
@dudakp yah you can do that

**Comment by dudakp** [comment]
CRA by default doesn't allow imports outside /src folder, is it ok to copy CODE_OF_CONDUCT to /src/Assets?

**Comment by ayan-biswas0412** [comment]
But the copy must be changed according to change in the file isn't it ?? @dudakp if it is then go ahead
