### ISSUE TITLE
[New work] Design a splash screen or loading screen while the app is Loading 

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#6]
The react app takes a time to load the specifications should be as below
1. It should be an SVG file.
2. Background colour should be there (take any ) but it should not be the default white.
3. Make PR to `develop` branch

**Comment by Ojay-dev** [comment]
Hi @ayan-biswas0412, I would like to work on this issue.

**Comment by ayan-biswas0412** [comment]
@Ojay-dev go ahead

**Comment by ayan-biswas0412** [comment]
Nice work @Ojay-dev
