### ISSUE TITLE
[New Work] Make the footer component more creative and animated

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#61]
**What is the work should be done please be clear and short about the work**
Search over internet take ideas and make one creative animated footer component

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Be creative and explore more

**The Best way to implement this (if any) **
NA

**Additional context** 
NA

**Comment by devblin** [comment]
Hey, I would like to work on this issue. Can you assign this to me ?

**Comment by ayan-biswas0412** [comment]
> Hey, I would like to work on this issue. Can you assign this to me ?
yah sure @devblin go ahead
