### ISSUE TITLE
[New Work] Make a panel in which simple mathematical equation can be written

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#62]
**What is the work should be done please be clear and short about the work**
Be creative and make a panel in which simple mathematical functions can be written and render the component in HomePage.js

**What the work is all about? Is there any specific files that need to be changed please include those.**
Just the panel should take input simple mathemital functions (simple integration , derivative )

**The Best way to implement this (if any) **
Be creative there is no strict way to do it

**Additional context** 
NA

**Comment by theamritanair** [comment]
I would like to work on this issue

**Comment by ayan-biswas0412** [comment]
Yah @theamritanair go ahead

**Comment by ayan-biswas0412** [comment]
nice work @theamritanair
