### ISSUE TITLE
[New Work] Make a data point generation funtions

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#67]
**What is the work should be done please be clear and short about the work**
Use any available package and make a function which accepts simple mathematical funtions as input and generate data points .

**What the work is all about ? Is there any specific files that need to be changed please include those.**
make a folder api in src and make your work done there 

**The Best way to implement this (if any) **
Research on this topic more and then do creatively 

**Additional context** 
NA

**Comment by sprakash57** [comment]
Can I pick this up?

**Comment by ayan-biswas0412** [comment]
@sprakash57 yeah go ahead

**Comment by sprakash57** [comment]
@ayan-biswas0412  i have raisd PR [https://github.com/indeplot/indeplot/pull/104](https://github.com/indeplot/indeplot/pull/104).

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 i have raisd PR #104.

but your function is generating random data points it has no input option

**Comment by sprakash57** [comment]
You mean on ui?

**Comment by ayan-biswas0412** [comment]
> You mean on ui? By going through the issue, i thought you are asking for a function inside src/api, thats all.

ohhk ohk i will make a separate issue for that @sprakash57 good work anyways

**Comment by sprakash57** [comment]
Please assign that seperate issue to me as well. I will create a component for it.

**Comment by ayan-biswas0412** [comment]
@sprakash57 yeah i will do it

**Comment by ayan-biswas0412** [comment]
See this https://github.com/indeplot/indeplot/issues/105 @sprakash57 i am assigningyou to this
