### ISSUE TITLE
[New Work] Make a chart colour selector panel

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#75]
**What is the work should be done please be clear and short about the work**
![image](https://user-images.githubusercontent.com/52851184/96374267-52147500-118f-11eb-8915-b6997a7927df.png)

Add a colour picker tool just beside the select chart type button which will change the base colour of the chart 

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Cehck the src/components folder you will understand how this works and also Homepage.js

**The Best way to implement this (if any) **
Be craetive and make your work eye appeling 

**Additional context** 
NA

**Comment by sprakash57** [comment]
Shall I pick this up?

**Comment by ieshaan12** [comment]
@sprakash57 I started working on it for a bit, and I'm almost done, I'm sorry for not informing but can I take this up?

**Comment by ieshaan12** [comment]
@ayan-biswas0412 Could you say what all colours you'd like?

**Comment by ayan-biswas0412** [comment]
@ieshaan12 can you make a colour picker like the html colour pickers which generate colour hex code based on mouse pointer selection ..we want that thing..

**Comment by ayan-biswas0412** [comment]
> Shall I pick this up?

Yeah you can do this..

**Comment by ayan-biswas0412** [comment]
> @sprakash57 I started working on it for a bit, and I'm almost done, I'm sorry for not informing but can I take this up?

@ieshaan12 @sprakash57 there is nothing to worry about you both can do this and both of your contribution we will accept so make your PRs against your work so no prblm

**Comment by sprakash57** [comment]
@ayan-biswas0412 I have raised PR [https://github.com/indeplot/indeplot/pull/81](https://github.com/indeplot/indeplot/pull/81) for review.

**Comment by ayan-biswas0412** [comment]
Nice work @sprakash57
