### ISSUE TITLE
[New Work] Change the Text and add theme

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#79]
**What is the work should be done please be clear and short about the work**
![image](https://user-images.githubusercontent.com/52851184/96377181-5ea1c900-11a1-11eb-999c-9bd3828b5faa.png)
change the text This is is the Home Page and This coding style should be followed to => Plot your own functions with ease
And make a radio button in the right which will toogle between light and dark theme like hacktoberfest website

**What the work is all about ? Is there any specific files that need to be changed please include those.**
NA

**The Best way to implement this (if any) **
show the maximum creativity

**Additional context** 
NA

**Comment by lakshyaTaragi** [comment]
I would like to try this

**Comment by ayan-biswas0412** [comment]
@lakshyaTaragi yeah go ahead

**Comment by ayan-biswas0412** [comment]
good work @lakshyaTaragi
