### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rdhaundiyal-indeed** [indeplot/indeplot#83]
**Describe the bug**
Sample data for generating charts is missing label.

**To Reproduce**
1. Go to Home page
2. Select any chart type to display
3. Notice that the displayed graph has only 4 data points

**Expected behavior**
As per the the sample data in HomePage.js file, there should be 5 data points
        this.state = {
            data: [65, 59, 80, 81, 56],
            labels: ['SampleX1', 'SampleX2', 'SampleX3', 'SampleX4']
        }
The issue exists because there are 5 data points but only 4 labels

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome
 - Version: n/a

**Comment by rdhaundiyal-indeed** [comment]
I can fix this as a followup to my hacktoberfest PR for adding a Polar chart. Did not want to do two things in one change list. Thanks.

**Comment by ayan-biswas0412** [comment]
@rdhaundiyal-indeed yeah you can fix the bug in  a separate PR and you will get 2 PRs for hacktoberfest

**Comment by ayan-biswas0412** [comment]
Nice work @rdhaundiyal-indeed
