### ISSUE TITLE
[New Work] Make a component which takes input data points and plot in the graph

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#93]
**What is the work should be done please be clear and short about the work**
Make a panel in the homepage just below the code editor which takes input the x-y coordinate values and plots in the graph
And there should be a button named Render which onclick the chart will be rendered

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Make component in src/components and render it in homepage

**The Best way to implement this (if any) **
NA

**Additional context** 
NA

**Comment by MissyM2** [comment]
Hi, there, can I work on this?

**Comment by ayan-biswas0412** [comment]
@MissyM2 yeah why not , your previous work is super awesome
