### ISSUE TITLE
[New Work] Modify the Line and Bar chart component

### ISSUE THREAD

**Issue by ayan-biswas0412** [indeplot/indeplot#95]
**What is the work should be done please be clear and short about the work**
Make a slider which will scale the line and bar chart component like for now it is fixed in a specified scaling but please make such that it can be converted into any scale

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Be creative and do whatever you want just by keeping the file structure and coding pattern same

**The Best way to implement this (if any) **
NA

**Additional context** 
NA

**Comment by ansh-saini** [comment]
Hey. Can you tell me exactly what do you mean by "scale"?
Do you mean the visual size of the chart?
Or do you mean the scale of all the values should go up (for example: 9 becomes 9000)

**Comment by ayan-biswas0412** [comment]
If graph has the following points say (1,1) , (2,4) , (3,6)  so here 
maximum value and minimum value of x is  1 and 3 so the graph will be plotted according to that now i want to show coordinate 1 to 20 then the graph will be smaller in terms of visualization and somehow streched or shrinked
